// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMqiux-iY6SlwwyG59q0lpY2HKcyOG3tM',
    appId: '1:977815128634:web:c4151f0cfe5a7308228303',
    messagingSenderId: '977815128634',
    projectId: 'healthyfit-bf235',
    authDomain: 'healthyfit-bf235.firebaseapp.com',
    storageBucket: 'healthyfit-bf235.appspot.com',
    measurementId: 'G-M1TFFB5296',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA68JumUaZe_rrM0uhn8KWvnZvLFGYmURg',
    appId: '1:977815128634:android:d446693e028bd63c228303',
    messagingSenderId: '977815128634',
    projectId: 'healthyfit-bf235',
    storageBucket: 'healthyfit-bf235.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-DuL8M0AesAwwINX76ZonPqT0mRGBj68',
    appId: '1:977815128634:ios:fe099fa6d3c150f4228303',
    messagingSenderId: '977815128634',
    projectId: 'healthyfit-bf235',
    storageBucket: 'healthyfit-bf235.appspot.com',
    iosBundleId: 'com.example.healthyfitapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-DuL8M0AesAwwINX76ZonPqT0mRGBj68',
    appId: '1:977815128634:ios:fe099fa6d3c150f4228303',
    messagingSenderId: '977815128634',
    projectId: 'healthyfit-bf235',
    storageBucket: 'healthyfit-bf235.appspot.com',
    iosBundleId: 'com.example.healthyfitapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMqiux-iY6SlwwyG59q0lpY2HKcyOG3tM',
    appId: '1:977815128634:web:f1004e64062b2dad228303',
    messagingSenderId: '977815128634',
    projectId: 'healthyfit-bf235',
    authDomain: 'healthyfit-bf235.firebaseapp.com',
    storageBucket: 'healthyfit-bf235.appspot.com',
    measurementId: 'G-Y5Y5ZXBXC0',
  );
}
